### ISSUE TITLE
How to fill match score

### ISSUE THREAD

**Issue by tsagita** [dolejska-daniel/bracket-generator#1]
Hi daniel, awesome code and useful.

But how to fill score in every match?

I see you have function public function fillByMatchList()

~ Thank you ~

**Comment by dolejska-daniel** [comment]
Hello and thank you for you interest in this little humble library!

I'm not really up-to date with the implementation as it has been quite some time since I've created this library. I'll try to look into it tomorrow and I'll let you know if I find out anything!

What I think is - filling the bracket means creating it again. Try reverse engineering the code in function `Bracket::createFromList` or just wait for me :smile_cat:.

**Comment by dolejska-daniel** [comment]
@tsagita - I've checked out some [Wiki pages](https://github.com/dolejska-daniel/bracket-generator/wiki/Creating-bracket) I've wrote back then _(I had literally no idea I did that)_ and I think you can find pretty useful info there - so check them out!

Please let me know whether it hepled or not. Thanks! :smiley:

**Comment by dolejska-daniel** [comment]
Hello again, @tsagita!

I've added a few usage examples to [examples](https://github.com/dolejska-daniel/bracket-generator/tree/master/examples) directory in 99d30e8d7153861870a0aa35d72b479e3abeda6d. Feel free to check them out 😎! I hope they will help you in some way.

Daniel

**Comment by tsagita** [comment]
Awesome, Thanks Bro !
